=== fktrcfylhrj/ELabs/lab3/src/main/java/medicinalPreparations.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:xs="http://www.w3.org/1999/XSL/Transform"
        targetNamespace="http://www.example.org/preparations"
        xmlns:tns="http://www.example.org/preparations" elementFormDefault="qualified">
    <element name="preparations">
        <complexType>
            <sequence>
                <element name="preparation" maxOccurs="unbounded">
                    <complexType>
                        <sequence>
                            <element name="name" type="tns:correctName"/>
                            <element name="type" type="tns:correctName" />
                            <element name="pharm" type="tns:correctName" />
                            <element name="group">
                                <complexType>
                                    <choice>
                                        <element name="antibiotic"/>
                                        <element name="analgesic"/>
                                        <element name="vitamin"/>
                                        <element name="antimicrobial"/>
                                        <element name="antidepressant"/>
                                        <element name="complex-action"/>
                                        <element name="tranquilizing_agent"/>
                                    </choice>
                                </complexType>
                            </element>
                            <element name="analogs">
                                <complexType>
                                    <sequence>
                                        <element name="analog" type="tns:correctName" maxOccurs="unbounded"/>
                                    </sequence>
                                </complexType>
                            </element>
                            <element name="versions">
                                <complexType>
                                    <sequence>
                                        <element name="version" maxOccurs="unbounded">
                                            <complexType>
                                                <choice>
                                                    <element name="pills">
                                                        <complexType>
                                                            <sequence>
                                                                <element name="manufacturers" type="tns:manufacturers"/>
                                                            </sequence>
                                                        </complexType>
                                                    </element>
                                                    <element name="capsules">
                                                        <complexType>
                                                            <sequence>
                                                                <element name="manufacturers" type="tns:manufacturers"/>
                                                            </sequence>
                                                        </complexType>
                                                    </element>
                                                    <element name="powder">
                                                        <complexType>
                                                            <sequence>
                                                                <element name="manufacturers" type="tns:manufacturers"/>
                                                            </sequence>
                                                        </complexType>
                                                    </element>
                                                    <element name="drops">
                                                        <complexType>
                                                            <sequence>
                                                                <element name="manufacturers" type="tns:manufacturers"/>
                                                            </sequence>
                                                        </complexType>
                                                    </element>
                                                    <element name="syrup">
                                                        <complexType>
                                                            <sequence>
                                                                <element name="manufacturers" type="tns:manufacturers"/>
                                                            </sequence>
                                                        </complexType>
                                                    </element>
                                                    <element name="spray">
                                                        <complexType>
                                                            <sequence>
                                                                <element name="manufacturers" type="tns:manufacturers"/>
                                                            </sequence>
                                                        </complexType>
                                                    </element>
                                                </choice>
                                            </complexType>
                                        </element>
                                    </sequence>
                                </complexType>
                            </element>
                        </sequence>
                        <attribute name="id" type="ID" use="required" />
                    </complexType>
                </element>
            </sequence>
        </complexType>
    </element>

    <complexType name="manufacturers">
            <sequence>
                <element name="manufacturer" maxOccurs="unbounded">
                    <complexType>
                        <sequence>
                            <element name="name" type="string"/>
                            <element name="certificate">
                                <complexType>
                                    <sequence>
                                        <element name="number" type="positiveInteger"/>
                                        <element name="dateOfIssuance" type="date"/>
                                        <element name="expirationDate" type="date"/>
                                        <element name="registeringOrganization" type="string"/>
                                    </sequence>
                                </complexType>
                            </element>
                            <element name="package">
                                <complexType>
                                    <sequence>
                                        <element name="type" type="string"/>
                                        <element name="amount" type="positiveInteger"/>
                                        <element name="cost">
                                            <complexType>
                                                <sequence>
                                                    <element name="currency" type="tns:currency"/>
                                                    <element name="value">
                                                        <simpleType>
                                                            <restriction base="double">
                                                                <minInclusive value="0.01"/>
                                                            </restriction>
                                                        </simpleType>
                                                    </element>
                                                </sequence>
                                            </complexType>
                                        </element>
                                    </sequence>
                                </complexType>
                            </element>
                            <element name="dosage">
                                <complexType>
                                    <sequence>
                                        <element name="value">
                                            <simpleType>
                                                <restriction base="string">
                                                    <pattern value="[1-9]+[0-9]* [a-z]*"/>
                                                </restriction>
                                            </simpleType>
                                        </element>
                                        <element name="times" type="positiveInteger"/>
                                        <element name="period" type="string"/>
                                    </sequence>
                                </complexType>
                            </element>
                        </sequence>
                    </complexType>
                </element>
            </sequence>
    </complexType>

    <simpleType name="currency">
        <restriction base="string">
            <enumeration value="RUR"/>
            <enumeration value="EUR"/>
            <enumeration value="USD"/>
            <enumeration value="GBP"/>
            <enumeration value="INR"/>
            <enumeration value="JPY"/>
            <enumeration value="AUD"/>
            <enumeration value="BRL"/>
            <enumeration value="CAD"/>
            <enumeration value="CNY"/>
            <length value="3"/>
        </restriction>
    </simpleType>

    <simpleType name="correctName">
            <restriction base="string">
                <pattern value="[a-zA-Z]+-*[a-zA-Z]+"/>
            </restriction>
    </simpleType>
</schema>

=== fktrcfylhrj/ELabs/lab3/src/main/java/medicinalPreparations.xml
<?xml version="1.0" encoding="UTF-8"?>
<preparations xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xmlns="http://www.example.org/preparations" xsi:schemaLocation="http://www.example.org/preparations medicinalPreparations.xsd">
    <preparation id="p201">
        <name>Korvalol</name>
        <type>Sedative</type>
        <pharm>Korvalol-pharm</pharm>
        <group>
            <tranquilizing_agent/>
        </group>
        <analogs>
            <analog>Valocardin</analog>
        </analogs>
        <versions>
            <version>
                <pills>
                    <manufacturers>
                        <manufacturer>
                            <name>Farmak</name>
                            <certificate>
                                <number>666123</number>
                                <dateOfIssuance>2021-09-09</dateOfIssuance>
                                <expirationDate>2051-09-09</expirationDate>
                                <registeringOrganization>public health Ministry</registeringOrganization>
                            </certificate>
                            <package>
                                <type>box</type>
                                <amount>20</amount>
                                <cost>
                                    <currency>RUR</currency>
                                    <value>200</value>
                                </cost>
                            </package>
                            <dosage>
                                <value>50 mg</value>
                                <times>2</times>
                                <period>day</period>
                            </dosage>
                        </manufacturer>
                    </manufacturers>
                </pills>
            </version>
        </versions>
    </preparation>

    <preparation id="p202">
        <name>Paracetamol</name>
        <type>Analgetic</type>
        <pharm>paracatamol-pharm</pharm>
        <group>
            <analgesic/>
        </group>
        <analogs>
            <analog>Nimesil</analog>
            <analog>Arbidol</analog>
            <analog>Ibuklin</analog>
        </analogs>
        <versions>
            <version>
                <pills>
                    <manufacturers>
                        <manufacturer>
                            <name>Paracetamol-manufacturer</name>
                            <certificate>
                                <number>228</number>
                                <dateOfIssuance>1950-01-01</dateOfIssuance>
                                <expirationDate>2050-01-02</expirationDate>
                                <registeringOrganization>public health Ministry</registeringOrganization>
                            </certificate>
                            <package>
                                <type>box</type>
                                <amount>20</amount>
                                <cost>
                                    <currency>USD</currency>
                                    <value>4</value>
                                </cost>
                            </package>
                            <dosage>
                                <value>45 mg</value>
                                <times>3</times>
                                <period>day</period>
                            </dosage>
                        </manufacturer>
                        <manufacturer>
                            <name>Another-PM</name>
                            <certificate>
                                <number>1999</number>
                                <dateOfIssuance>2000-12-12</dateOfIssuance>
                                <expirationDate>3000-10-10</expirationDate>
                                <registeringOrganization>public health Ministry</registeringOrganization>
                            </certificate>
                            <package>
                                <type>box</type>
                                <amount>25</amount>
                                <cost>
                                    <currency>EUR</currency>
                                    <value>3</value>
                                </cost>
                            </package>
                            <dosage>
                                <value>49 mg</value>
                                <times>1</times>
                                <period>8 hours</period>
                            </dosage>
                        </manufacturer>
                    </manufacturers>
                </pills>
            </version>
            <version>
                <powder>
                    <manufacturers>
                        <manufacturer>
                            <name>Powder-mr</name>
                            <certificate>
                                <number>5555</number>
                                <dateOfIssuance>2001-11-09</dateOfIssuance>
                                <expirationDate>2051-11-09</expirationDate>
                                <registeringOrganization>public health Ministry</registeringOrganization>
                            </certificate>
                            <package>
                                <type>box with small packets</type>
                                <amount>10</amount>
                                <cost>
                                    <currency>RUR</currency>
                                    <value>321</value>
                                </cost>
                            </package>
                            <dosage>
                                <value>60 mg</value>
                                <times>3</times>
                                <period>day</period>
                            </dosage>
                        </manufacturer>
                    </manufacturers>
                </powder>
            </version>
        </versions>
    </preparation>
</preparations>
